Updated queue ID length and added '-s' option
brablc/postfix-tools pull request #1
Opened 2017-03-02 21:56 UTC by MarcoMoreno

Great tool!  I changed the postfix queue id length from 11 to 10 to support servers having the latter.  Also added a '-s' option to include a separator between messages for easier scanning.  Finally, updated the usage block to use $me instead of hardcoded 'pflogrep' to support a renamed file.

(I named my script to 'postgreplog' since I'll never remember it the next time I need to use it.  Tab completion will help me remember with 'post<tab>' since it's similar to the family of other postfix commands.)

2017-03-02 23:57 UTC, brablc requested changes
Nice touch.

2017-03-02 23:57 UTC, brablc commented on pflogrep
> +        next unless /: (([0-9A-Z]{10})|NOQUEUE)/;
We would need {10,11} here to support both.

2017-03-03 02:20 UTC, MarcoMoreno commented on pflogrep
> +        next unless /: (([0-9A-Z]{10})|NOQUEUE)/;
I suppose you're right for the sake of precision even though it's likely to work fine as is. 

However, I just learned that postfix now has an option to support long ids of 52 characters which are lower case so it should probably be:

`next unless /: (([0-9A-Za-z]{10,})|NOQUEUE)/;`

2017-03-03 16:17 UTC, brablc commented on pflogrep
> +        next unless /: (([0-9A-Z]{10})|NOQUEUE)/;
It is 52-character alphabet http://www.postfix.org/postconf.5.html , the length is 15 if I read correctly. So lets make it `([0-9A-Za-z]{10,15})`? Would you?

2017-03-03 16:17 UTC, brablc commented on pflogrep
> +        next unless /: (([0-9A-Z]{10})|NOQUEUE)/;
Actually `([0-9A-Zb-z]{10,15})`, would show we have read the specs better.

2017-03-03 19:11 UTC, MarcoMoreno commented
You're right - I didn't read the spec very closely.  I'm very new to pull requests so I hope I did this properly.

2017-03-06 20:08 UTC, MarcoMoreno commented
So is there anything more you need me to do before you merge this?  As I said, I'm new to pull requests so I don't know if I did all this properly.

2017-03-07 08:41 UTC, brablc approved these changes
Nice job, thank you.

2017-03-07 08:41 UTC, merged

2017-03-07 08:47 UTC, brablc commented
BTW `pflogrep` name was used because of existing companion tool `pflogsumm`